### ISSUE TITLE
unknown schema io.k8s.api.rbac.authorization.v1.ClusterRole

### ISSUE THREAD

**Issue by r1ckr** [chuckha/kubeyaml#18]
According to the KubeAPI this is a valid schema, but it appears as unknown:
```
unknown schema io.k8s.api.rbac.authorization.v1.ClusterRole

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```
