### ISSUE TITLE
Pod resource's request and limit memory value with lowercase 'mi' wasn't caught 

### ISSUE THREAD

**Issue by mensis-labs** [chuckha/kubeyaml#20]
This invalid file wasn't proper checked

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    spec:
      containers:
      - name: "3"
        image: "nginx:1.7.9"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16mi"
            cpu: "5m"
          limits:
            memory: "32mi"
            cpu: "10m"
```

It should be *16Mi* and *32Mi*
