### ISSUE TITLE
JSON.parse error when validating YAML

### ISSUE THREAD

**Issue by jazzdan** [chuckha/kubeyaml#6]
When validating this YAML:

```yaml
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: client
          image: dockerhub.io/client:0.1.0-dev
          imagePullPolicy: Always
          ports:
          - name: http-client
            containerPort: 9000
            protocol: TCP
        - name: backend
          image: dockerhub.io/backend:0.1.0-dev
          imagePullPolicy: Always
          ports:
          - name: http-backend
            containerPort: 8000
            protocol: TCP
          volumeMounts:
          - name: config
            mountPath: /etc/backend
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: fe-backend
            items:
            - key: config
              path: config.yam
```
I click "Validate" and nothing happens. In the web console I see:

```
submit { target: form#input.tile.is-child, isTrusted: true, srcElement: form#input.tile.is-child, currentTarget: form#input.tile.is-child, eventPhase: 2, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
bundle.js:1:2314

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]
```
