### ISSUE TITLE
discuss.kubernetes.io feedback

### ISSUE THREAD

**Issue by chuckha** [chuckha/kubeyaml#9]
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
  name: test
  namespace: tester
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: tes
  sessionAffinity: None
  type: Airflow
```

A user believes this is invalid but reporting valid.

https://discuss.kubernetes.io/t/kubeyaml-com-an-online-kubernetes-yaml-validator/2856
